<!-- reference from https://github.com/CodeAT21/How-to-Integrate-PayPal-REST-API-Payment-Gateway-in-PHP -->

<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInit728f96e67824ff0c88d9b31fcd5c7681::getLoader();
